### ISSUE TITLE
Propbaly you could simplify random logic

### ISSUE THREAD

**Issue by MaxGraey** [XRPL-Labs/AssemblyScript-Sample#1]
```ts
export function main(): void {
  const someArray = [someFn(), anotherFn()]
  jsHello(someArray[i32(Math.round(f64(Math.random())))])
}
```
I guess it should simpler and more logical:

**Updated example**:
```ts
export function main(): void {
  const someArray = [someFn(), anotherFn()];
  jsHello(someArray[i32(Math.random() > 0.5)]);
}
```

**Comment by WietseWind** [comment]
Haha wow, yep. Thanks. You can tell I needed a coffee ;)

**Comment by MaxGraey** [comment]
No, I realized your sample is ok due to you use `[someFn(), anotherFn()]` instead `[someFn, anotherFn]`, so my comment was wrong. But you could simplify random stuff as I suggested)

**Comment by WietseWind** [comment]
I noticed. I meant the rounding part ;) 

Otherwise it'd get me `ERROR TS2757: Type '() => i32' has no call signatures` indeed.
